### ISSUE TITLE
Consuming apps attempt to resolve your test in-repo addons

### ISSUE THREAD

**Issue by pkmh** [salsify/ember-css-modules#137]
Hey all,

So my app uses ember-cli-notifications, which requires ember-css-modules as a dependency, and whenever I build the app I get the following warnings in my terminal:

`WARNING: The 'package.json' file for the addon at /Users/patrickhickey/dev/someApp/ember/node_modules/ember-css-modules
WARNING:   specifies invalid, malformed or missing addons at relative paths
WARNING:     'tests/dummy-addon'
WARNING:     'tests/dummy-sass-addon'
WARNING:     'tests/dummy-less-addon'`

I would like to resolve this, but I'm not sure how you would like to proceed. I imagine you want to keep those tests, so I thought we could use ember-cli-addon-tests - like whats outlined in this other issue: https://github.com/linkedin/css-blocks/issues/214

Cheers,
-Patrick

**Comment by buschtoens** [comment]
Is this potentially related to #105?

**Comment by dfreeman** [comment]
@pkmh Thanks for reporting the issue! It looks like `ember-cli-notifications` needs to be updated to a more recent ember-css-modules version—this issue [should be fixed](https://github.com/salsify/ember-css-modules/commit/1bbf2f2afdf54bb0e21246eb83652a6d7e4d55dc) since our first 1.0 beta. (If you check the `package.json` here, there are no addon `paths` specified 🙂)

I'm going to go ahead and close this issue since there's nothing we can do from this end, but please let me know if I've missed something.
