### ISSUE TITLE
feature request: nested global 

### ISSUE THREAD

**Issue by knownasilya** [salsify/ember-css-modules#163]
I'd like to do the following:

```css
:global {
  .selector1 {}

  .selector2 {}
}
```

Currently the `:global` disappears but the braces are left making it invalid.

**Comment by buschtoens** [comment]
Did you already try adding [`postcss-nested`](https://github.com/postcss/postcss-nested) (and [`postcss-nested-ancestors`](https://github.com/toomuchdesign/postcss-nested-ancestors), if you like) to the [`before` section](https://github.com/salsify/ember-css-modules/blob/master/docs/POSTCSS.md#beforeafter-postcss-plugins)?

[This is the config](https://github.com/ClarkSource/ember-css-modules-config/blob/master/lib/clark-plugin.js#L36-L42) that I use myself and AFAIK what you suggested works with it.

**Comment by knownasilya** [comment]
No, but will give it a go. Thanks!

**Comment by knownasilya** [comment]
Hum, I'm using sass plugin, so actually this shouldn't be needed right?

**Comment by buschtoens** [comment]
[`ember-css-modules-sass`](https://github.com/dfreeman/ember-css-modules-sass/blob/8651f785c22ee278cce1c1fe96c395b02d46dac1/index.js#L26-L32) only sets the `sass` syntax parser, so that PostCSS doesn't crash, but doesn't actually perform any transforms, like unwrapping nesting or interpolating variables. `ember-css-modules` then takes all individual `.scss` files, concatenates them and transpiles CSS Modules concepts, like `@value` and `:global`. The concatenated `.scss` is then passed through to `ember-cli-sass`, which then actually transforms it to `.css`. But since `:global` was already transpiled prior to that, the transform breaks.

**Comment by knownasilya** [comment]
That works.
