### ISSUE TITLE
Style inheritance when extending another component

### ISSUE THREAD

**Issue by duro** [salsify/ember-css-modules#35]
I am looking to have a base component that other components extend from. The base component would have some local styles in it's styles.css, and then the extended components would also have some of their own local styles.

Is there already a good way to do this?

Right now I am doing something really janky, and having the sub-classed compoents use the `composes` property:

```
// /app/features/components/app-card/styles.css

.card {
  composes: card from '../base-card/styles';

  &.app-card {
    .icon {
      .inner-container {
        span {
          display: block;
          width: 100%;
          height: 100%;
          background-size: cover;
        }
      }
    }
  }
}

.icon {
  composes: icon from '../base-card/styles';
}

.inner-container {
  composes: inner-container from '../base-card/styles';
}

.name {
  composes: name from '../base-card/styles';
}
```

```
// /app/features/components/base-card/styles.css

.card {
  border: solid 1px rgb(221, 221, 221);
  border-radius: 3px;
  padding: 6px;

  &:hover {
    border-color: rgb(60, 169, 231);

    .name {
      background-color: rgb(190, 217, 231);
    }
  }

  .icon {
    padding-bottom: 100%;
    position: relative;

    .inner-container {
      position: absolute;
      z-index: 100;
      top: 0; left: 0; bottom: 0; right: 0;
    }
  }

  .name {
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: center;
    background-color: rgb(221, 221, 221);
    padding: 3px;
    height: 70px;

    h4 {
      margin: 0;
    }
  }
}
```

**Comment by dfreeman** [comment]
In general, component inheritance tends to be difficult to work with because HTML/Handlebars templates don't have any notion inheritance. As you rightly point out, CSS modules compound this problem by making you also repeat your class usage everywhere.

One option would be to do something like this:
```js
// app/features/components/base-card/component.js
import styles from './styles';

export default Component.extend({
  baseStyles: styles
  // ...
});
```

You'd then be able to reference the base class's styles like `class={{baseStyles.name}}` in the template for your derived component templates like `app-card`.

**However**, if possible I would take a step back and look at whether you might be able achieve the reuse you're after with composition rather than inheritance. In general I've found composing derived components from more general base ones to be a lot less painful than trying to manage such reuse via subclassing.

What if instead of extending `base-card`, `app-card`'s template just invoked `{{base-card}}`? You could imagine using something like [ember-block-slots](https://github.com/ciena-blueplanet/ember-block-slots) or [ember-named-yields](https://github.com/knownasilya/ember-named-yields) to make different sections of your base card overridable on a case by case basis, without having to duplicate the markup of the entire card structure.

Looking at your `app-card` example, it looks like you're wanting to adjust the styles for one fairly deeply-nested class. Without knowing the full details, the icon might be a good candidate to be a slot with some default content in `base-card` that could be overridden in `app-card`'s usage of it.

[ember-power-select](http://www.ember-power-select.com/docs/architecture) is a good example of a component that's built up this way.

**Comment by dfreeman** [comment]
@duro I'm going to go ahead and close this since I don't think there are any actionable changes here for the addon, but if you have further thoughts or questions please feel free to reopen or start a new issue.
