### ISSUE TITLE
Seems to mess up addon assets

### ISSUE THREAD

**Issue by rwwagner90** [salsify/ember-css-modules#44]
I have a dependency on headroom.js, in my addon, and it can no longer find it, seems to have undefined in the path.

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/rwwagner/shipshape/ember-3d-nav/tmp/source_map_concat-input_base_path-KLVmmqhC.tmp/0/undefined/headroom.js/dist/headroom.min.js'
```

**Comment by dfreeman** [comment]
To make sure I've got the dependency graph right, ember-3d-nav depends on headroom.js, and adding ember-css-modules as a dependency of ember-3d-nav breaks ember-headroom?

That `undefined` in the path seems pretty suspicious — based on [this line](https://github.com/shipshapecode/ember-headroom/blob/master/index.js#L18), I'm guessing `app.bowerDirectory` is somehow getting lost?

**Comment by rwwagner90** [comment]
@dfreeman yeah, sounds more or less correct. I started working on implementing it in this branch https://github.com/shipshapecode/ember-3d-nav/tree/css-modules

**Comment by dfreeman** [comment]
This actually looks unrelated to ember-css-modules — if I remove it from the `package.json` for ember-3d-nav on that branch, I still see the same error.

**Comment by dfreeman** [comment]
It looks like the reason this appeared to be working before was because `_super` was being called incorrectly in ember-3d-nav's `included()`, and so the ember-headroom dependency was never being activated for the addon, only for the dummy app.

Since you removed the `included()` implementation on that branch, the bug reared its head.

**Comment by rwwagner90** [comment]
@dfreeman could you please elaborate on what I am doing incorrectly in included? Would definitely be nice to not have to `addAddonToProject` for consuming apps, if I could.

Either way, with or without an included hook, there are errors.

**Comment by dfreeman** [comment]
@rwwagner90 I know we've talked in Slack some since this was filed, I'm just going through some issue cleanup. Are you still running into this issue?

Several addons are successfully using ember-css-modules today, so I know this works at least in the general case, but I'm not sure if we ever got to the bottom of what was happening here.

**Comment by rwwagner90** [comment]
@dfreeman I am unsure if there are still issues or not. We can close for now, and I will open a new issue if I encounter more problems. Thanks!
