### ISSUE TITLE
Relative paths to files

### ISSUE THREAD

**Issue by FransTwisk** [salsify/ember-css-modules#46]
I'm using 'postcss-inline-svg' and I would like to access svg files that are relative to the style.css in each component:

> component/
> -- template.hbs
> -- component.js
> -- styles.css
> -- assets/
> ---- icon.svg

When I tried to access 'assets/icon.svg' in 'styles.css', it can't find it and throws an error:

`background-image: svg-load('assets/icon.svg';`

Are the paths I can use in the specific component's style.css relative to itself? The plugin is run before css-modules. It doesn't seem to work when '@import'ing a relative file, using 'postcss-import' either.

**Comment by dfreeman** [comment]
Can you provide more detail on what you're trying to do with `@import`?

For the SVGs, the issue is currently that non-CSS files are being filtered out prior to processing. We can likely fix that relatively easily, though it may be a bit tricky for addons since ember-cli filters out files whose extensions don't match a preprocessor by default.

**Comment by FransTwisk** [comment]
Actually the @import works as it should (must have done something wrong). 

For the SVG's: the 'postcss-inline-svg' plugin needs to be able to ready the files, so maybe there is a way to add the components path to be used when processing?

**Comment by dfreeman** [comment]
As a short-term solution, I think you could specify the root of your app as a base [path](https://github.com/TrySound/postcss-inline-svg#optionspath) to `postcss-inline-svg`, e.g.

```js
// ember-cli-build.js
cssModules: {
  plugins: [
    require('postcss-inline-svg')({
      path: path.join(__dirname, 'app')
    })
  ]
}
```

And then do something like:

```css
background-image: svg-load('components/my-component/assets/icon.svg');
```

That's obviously not ideal, since it's both verbose and a refactoring hazard, but I think it would at least let you move forward for the time being.

Longer term, I think we could aim for something like this:

```js
cssModules: {
  assetExtensions: ['svg'],
  plugins: {
    before: [require('postcss-inline-svg')]
  }
}
```

Where `assetExtensions` would allow you to specify a set of file extensions that should be included in the CSS processing pipeline and therefore available during processing at a relative path to the source file. Seem reasonable?

**Comment by FransTwisk** [comment]
Both solutions seem valid. I'll keep an eye out on any updates, thanks!
