### ISSUE TITLE
Addon usage not work in consumer app

### ISSUE THREAD

**Issue by nightire** [salsify/ember-css-modules#47]
I move all things related with ember-css-modules and postcss stack into an addon (also along with styles), follow the instructions on readme, it looks good for both addon itself and dummy app.

After then I install this addon to consumer ember app, things from inside the addon still works, but ember-css-modules won't process styles in the consumer app (I thought it would be).

Now I have to install ember-css-modules in consumer app again, and if some settings going to change, it has to be done in two or more projects. How to solve this?

Here is the addon repo: https://github.com/choice-form/ember-choice-ui, if it helps.

**Comment by nightire** [comment]
OMG, just found we cannot install ember-css-modules on both side, otherwise addon's styles won't be processed...crap, being struggled.

**Comment by dfreeman** [comment]
In Ember CLI (this isn't unique to ember-css-modules), all preprocessors like Babel, Sass, etc. only apply to the app or addon that they're a dependency of. If I install an addon like ember-tooltips, which uses ember-cli-sass for its styles, that doesn't automatically make it so that I can use Sass in my own application code. Similarly, installing an addon that uses ember-css-modules won't automatically apply ember-css-modules to the app that includes it.

If you want to manage the configuration ember-css-modules in one place, you could extract it into a small npm package and then do `cssModules: require('my-css-modules-config')` in both your app and addon.

**Comment by dfreeman** [comment]
For your follow on comment, I think I'll need more information. We're using ember-css-modules in a couple apps where some of their addons also use it, and haven't had any trouble.

Is your consuming app something public you can share? If not, can you create a small reproduction app showing the issue?

**Comment by nightire** [comment]
@dfreeman Thank you, my problem is can not use ember-css-modules both in addon and app at the same time.

I will consider a proper way to provide a reproduction app in recently days.

**Comment by nightire** [comment]
@dfreeman Hi, thanks again for your patience and detailed explanation, after retrying all over again, it finally works as great as we expected. Sorry for the false alarm 🍧 , I'm closing this.

**Comment by dfreeman** [comment]
No problem—I'm glad everything's working for you!
