### ISSUE TITLE
Generating addon.less using ember-css-modules in an addon

### ISSUE THREAD

**Issue by wattyrevBT** [salsify/ember-css-modules#71]
I'm having issues with the generation of the intermediate file in an Ember addon while using ember-cli-less. Here are two examples, one that works, and one that does not. I can't figure out why the one does not work:

# Working Example
## index.js
```javascript
        cssModules: {
            intermediateOutputPath: 'addon/styles/modules.less',
            extension: 'less',
            postcssOptions: {
                syntax: require('postcss-less')
            }
        },
```

## Structure of styles folder
```
> styles
    > components
        my-addon-component.less
    addon.less
    styles.less
```

## addon.less
```css
@import '/addon/styles/modules.less';
```

With this setup, the addon works fine, and the styles from my-addon-component.less, and from styles.less are included in the consuming application.

# Non-Working Example
## index.js
```javascript
        cssModules: {
            intermediateOutputPath: 'addon/styles/addon.less',
            extension: 'less',
            postcssOptions: {
                syntax: require('postcss-less')
            }
        },
```

## Structure of styles folder
```
> styles
    > components
        my-addon-component.less
    styles.less
```

In this setup, I would expect that addon.less would be generated by ember-css-modules before ember-cli-less attempts to process addon.less. I would expect that the styles would then end up in the consuming app, and would contain the contents of my-addon-component.less, and styles.less.

In reality, I get an error from ember-cli-less complaining about addon.less not existing. It can't be that it's not generated in time, because when it creates modules.less, that gets picked up by the @import.

I have the same sort of setup working in an Ember app, and it seems to generate the app.less for ember-cli-less to pickup and process.

Any idea what the deal is here? Why can I not use ember-css-modules to generate the addon.less for an addon?

**Comment by dfreeman** [comment]
Hi @wattyrevBT,

I _think_ the issue you're running into is that ember-cli is inconsistent in how its output gets placed between apps and addons — for apps you have to explicitly include the `app/styles` prefix, but for addons you would actually leave that out. If you check the [dummy-less-addon](https://github.com/salsify/ember-css-modules/blob/master/tests/dummy-less-addon/index.js) in the tests, it just specifies `'addon.less'` rather than `'addon/styles/addon.less'` as the `intermediateOutputPath`.

Can you give that a try? If it works and you have a couple minutes to open a PR to update the readme around `intermediateOutputPath` with addons, that would be fantastic — otherwise I'll just use this issue as a reminder to do that myself later 🙂

**Comment by wattyrevBT** [comment]
Ooooo, that did it, thanks. I'll make a quick fork and update that readme for you.

**Comment by dfreeman** [comment]
Thanks so much! Thank you also for the excellent issue — the info you gave made it super easy to track down what was going on.
