### ISSUE TITLE
Cannot parsing @supports rule with autoprefixer plugin

### ISSUE THREAD

**Issue by nightire** [salsify/ember-css-modules#78]
I made a reproduction app for this: https://github.com/very-geek/ecm-at-support-rule-bug, it only contains one css rule in `app/styles/application.css`, just run `ember s` will throw an error. If no `@supports` rules exist or don't use autoprefixer plugin will be fine.

BTW, I think it might not be ECM's problem, because I've try previous version and this bug still existed. I'm seeing this bug because I delete `yarn.lock` in one of my project, after `yarn install`, this bug appears. So it might be related with some upstream dependencies.

**Comment by nightire** [comment]
OK, I've managed to find the cause:

```diff
modified   yarn.lock
@@ -1527,11 +1527,11 @@ browserslist@^1.3.6, browserslist@^1.5.2:
     electron-to-chromium "^1.2.7"
 
 browserslist@^2.1.2, browserslist@^2.1.5:
-  version "2.2.0"
-  resolved "https://registry.yarnpkg.com/browserslist/-/browserslist-2.2.0.tgz#5e35ec993e467c6464b8cb708447386891de9f50"
+  version "2.2.1"
+  resolved "https://registry.yarnpkg.com/browserslist/-/browserslist-2.2.1.tgz#709048c57bf3bf9b382105c396a737ad525d948e"
   dependencies:
-    caniuse-lite "^1.0.30000701"
-    electron-to-chromium "^1.3.15"
+    caniuse-lite "^1.0.30000704"
+    electron-to-chromium "^1.3.16"
```

this bug only appears after this change has been applied, but I'm not familiar with browserslist, I can't see how it involves with this issue.

**Comment by dfreeman** [comment]
I believe `browserslist` is what powers the ability of tools like Autoprefixer and babel-preset-env to take expressions like `last 2 Chrome versions` and figure out what that means for feature support, so I think you're right that this is well outside the scope of what ECM is dealing with.

Incidentally, I'd recommend using `ember-cli-autoprefixer` rather than applying autoprefixer as a PostCSS plugin with ECM, since `ember-cli-autoprefixer` will apply to everything in your `vendor.css` as well.

**Comment by nightire** [comment]
Thanks for your advice, fortunately this bug has been fixed by upstream PR https://github.com/ai/browserslist/pull/161
